/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controlador_FRM_Automoviles;

/**
 *
 * @author MandoInuzuka
 */
public class GUI_InformacionAutomoviles extends javax.swing.JPanel {

    Controlador.Controlador_FRM_Automoviles controlador;
    int numeroRegistro;
    int resultado;

    public GUI_InformacionAutomoviles() {
        initComponents();
       

    }

    public int numeroRegistro(){
        
        int numero=1;
        
        resultado++;
        this.JT_NumeroRegistro.setText(""+resultado);
        
        resultado=numeroRegistro+numero;
        System.out.println(""+resultado);
        return numeroRegistro;
    }
    public void agregarEventos(Controlador_FRM_Automoviles controlador) {
        this.controlador = controlador;
    }
    
    public String[] devolverInformacion(){
    String arreglo[];
    arreglo =new String[4];
    arreglo[0]=this.JT_NumeroRegistro.getText();
    arreglo[1]=this.JT_NombreDueno.getText();
    arreglo[2]=this.JT_CedulaDueno.getText();
    arreglo[3]=this.JT_PlacaAutomovil.getText();
    return arreglo;
}
    
    public String devolverNumeroRegistro(){
    return this.JT_NumeroRegistro.getText();
}
public String devolverNombreDueno(){
    return this.JT_NombreDueno.getText();
}
public String devolverCedulaDueno(){
    return this.JT_CedulaDueno.getText();
}
public String devolverPlacaAutomovil(){
    return this.JT_PlacaAutomovil.getText();
}

public void mostrarInformacion(String[] arreglo){
    this.JT_NombreDueno.setText(arreglo[0]);
    this.JT_CedulaDueno.setText(arreglo[1]);
    this.JT_PlacaAutomovil.setText(arreglo[2]);
}
public void limpiar(){
    //this.JT_NumeroRegistro.setText("");
    this.JT_NombreDueno.setText("");
    this.JT_CedulaDueno.setText("");
    this.JT_PlacaAutomovil.setText("");
}
public void estadoInicial(){
    this.JT_NumeroRegistro.setEnabled(true);
    this.JT_NombreDueno.setEnabled(false);
    this.JT_CedulaDueno.setEnabled(false);
    this.JT_PlacaAutomovil.setEnabled(false);
}
public void deshabilitarNumeroRegistro(){
    this.JT_NumeroRegistro.setEnabled(false);
}
public void habilitarOpciones(){
    this.JT_NumeroRegistro.setEnabled(false);
    this.JT_NombreDueno.setEnabled(true);
    this.JT_CedulaDueno.setEnabled(true);
    this.JT_PlacaAutomovil.setEnabled(true);
}
public void habilitarAgregar(){
    this.JT_NumeroRegistro.setEnabled(false);
    this.JT_NombreDueno.setEnabled(true);
    this.JT_CedulaDueno.setEnabled(true);
    this.JT_PlacaAutomovil.setEnabled(true);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JT_NumeroRegistro = new javax.swing.JTextField();
        JT_NombreDueno = new javax.swing.JTextField();
        JT_CedulaDueno = new javax.swing.JTextField();
        JT_PlacaAutomovil = new javax.swing.JTextField();

        jLabel1.setText("Número de Registro");

        jLabel2.setText("Nombre del Dueño");

        jLabel3.setText("Cédula del Dueño");

        jLabel4.setText("Placa del Automóvil");

        JT_NumeroRegistro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                JT_NumeroRegistroKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JT_PlacaAutomovil, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(JT_CedulaDueno)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(25, 25, 25)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(JT_NombreDueno, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                            .addComponent(JT_NumeroRegistro))))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(JT_NumeroRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(JT_NombreDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(JT_CedulaDueno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JT_PlacaAutomovil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(35, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JT_NumeroRegistroKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JT_NumeroRegistroKeyPressed
        if (evt.getKeyCode() == 10) {
            controlador.buscar();
        }// TODO add your handling code here:
    }//GEN-LAST:event_JT_NumeroRegistroKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JT_CedulaDueno;
    private javax.swing.JTextField JT_NombreDueno;
    private javax.swing.JTextField JT_NumeroRegistro;
    private javax.swing.JTextField JT_PlacaAutomovil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables
}


